<?php

return [
    'GET' => [
        '/api/users' => ['UserApiController', 'index'],
        '/api/users-datatable' => ['UserDataTableController', 'index'],
        '/api/auth/me' => ['AuthApiController', 'me'],
        '/api/products' => ['ProductApiController', 'index'],
        '/api/categories' => ['CategoryApiController', 'index'],
        '/api/products/show' => ['ProductApiController', 'show'],
        '/api/orders' => ['OrderApiController', 'index'],
        '/api/orders/show' => ['OrderApiController', 'show'],
        '/api/invoices' => ['InvoiceApiController', 'index'],
        '/api/invoices/datatable' => ['InvoiceApiController', 'datatable'],
        '/api/invoices/show' => ['InvoiceApiController', 'show'],
        '/api/payments' => ['PaymentApiController', 'index'],
        '/api/payments/datatable' => ['PaymentApiController', 'datatable'],
        '/api/payments/show' => ['PaymentApiController', 'show'],
        '/api/customers' => ['CustomerApiController', 'index'],
        '/api/customers/datatable' => ['CustomerApiController', 'datatable'],
        '/api/customers/show' => ['CustomerApiController', 'show'],
        '/api/archives' => ['ArchiveApiController', 'index'],
        '/api/archives/datatable' => ['ArchiveApiController', 'datatable'],
        '/api/archives/show' => ['ArchiveApiController', 'show'],
        '/api/archives/export' => ['ArchiveApiController', 'exportCsv'],
        '/api/archives/trash' => ['ArchiveApiController', 'trash'],
        '/api/demos' => ['DemoApiController', 'index'],
        '/api/demos/datatable' => ['DemoApiController', 'datatable'],
        '/api/demos/show' => ['DemoApiController', 'show'],
        '/api/demos/export' => ['DemoApiController', 'exportCsv'],
        '/api/demos/trash' => ['DemoApiController', 'trash'],
    ],
    'POST' => [
        '/api/auth/login' => ['AuthApiController', 'login'],
        '/api/products/store' => ['ProductApiController', 'store'],
        '/api/products/update' => ['ProductApiController', 'update'],
        '/api/products/delete' => ['ProductApiController', 'delete'],
        '/api/categories/store' => ['CategoryApiController', 'store'],
        '/api/categories/update' => ['CategoryApiController', 'update'],
        '/api/categories/delete' => ['CategoryApiController', 'delete'],
        '/api/orders/store' => ['OrderApiController', 'store'],
        '/api/orders/update' => ['OrderApiController', 'update'],
        '/api/orders/delete' => ['OrderApiController', 'delete'],
        '/api/invoices/store' => ['InvoiceApiController', 'store'],
        '/api/invoices/update' => ['InvoiceApiController', 'update'],
        '/api/invoices/delete' => ['InvoiceApiController', 'delete'],
        '/api/payments/store' => ['PaymentApiController', 'store'],
        '/api/payments/update' => ['PaymentApiController', 'update'],
        '/api/payments/delete' => ['PaymentApiController', 'delete'],
        '/api/payments/bulk-delete' => ['PaymentApiController', 'bulkDelete'],
        '/api/customers/store' => ['CustomerApiController', 'store'],
        '/api/customers/update' => ['CustomerApiController', 'update'],
        '/api/customers/delete' => ['CustomerApiController', 'delete'],
        '/api/customers/bulk-delete' => ['CustomerApiController', 'bulkDelete'],
        '/api/archives/restore' => ['ArchiveApiController', 'restore'],
        '/api/archives/store' => ['ArchiveApiController', 'store'],
        '/api/archives/update' => ['ArchiveApiController', 'update'],
        '/api/archives/delete' => ['ArchiveApiController', 'delete'],
        '/api/archives/bulk-delete' => ['ArchiveApiController', 'bulkDelete'],
        '/api/demos/restore' => ['DemoApiController', 'restore'],
        '/api/demos/store' => ['DemoApiController', 'store'],
        '/api/demos/update' => ['DemoApiController', 'update'],
        '/api/demos/delete' => ['DemoApiController', 'delete'],
        '/api/demos/bulk-delete' => ['DemoApiController', 'bulkDelete'],
    ],
];
