<?php

return [
    'GET' => [
        '/' => ['DashboardController', 'index'],
        '/home' => ['HomeController', 'index'],
        '/login' => ['AuthController', 'login'],
        '/register' => ['AuthController', 'register'],
        '/logout' => ['AuthController', 'logout'],
        '/users' => ['UserController', 'index'],
        '/users/create' => ['UserController', 'create'],
        '/users/edit' => ['UserController', 'edit'],
        '/users/delete' => ['UserController', 'delete'],
        '/products' => ['ProductController', 'index'],
        '/products/create' => ['ProductController', 'create'],
        '/products/edit' => ['ProductController', 'edit'],
        '/products/delete' => ['ProductController', 'delete'],
        '/categories' => ['CategoryController', 'index'],
        '/products/show' => ['ProductController', 'show'],
        '/orders' => ['OrderController', 'index'],
        '/orders/create' => ['OrderController', 'create'],
        '/orders/edit' => ['OrderController', 'edit'],
        '/orders/delete' => ['OrderController', 'delete'],
        '/orders/show' => ['OrderController', 'show'],
        '/invoices' => ['InvoiceController', 'index'],
        '/invoices/create' => ['InvoiceController', 'create'],
        '/invoices/edit' => ['InvoiceController', 'edit'],
        '/invoices/delete' => ['InvoiceController', 'delete'],
        '/invoices/show' => ['InvoiceController', 'show'],
        '/payments' => ['PaymentController', 'index'],
        '/payments/create' => ['PaymentController', 'create'],
        '/payments/edit' => ['PaymentController', 'edit'],
        '/payments/delete' => ['PaymentController', 'delete'],
        '/payments/show' => ['PaymentController', 'show'],
        '/customers' => ['CustomerController', 'index'],
        '/customers/create' => ['CustomerController', 'create'],
        '/customers/edit' => ['CustomerController', 'edit'],
        '/customers/delete' => ['CustomerController', 'delete'],
        '/customers/show' => ['CustomerController', 'show'],
    ],
    'POST' => [
        '/login' => ['AuthController', 'login'],
        '/register' => ['AuthController', 'register'],
        '/users/create' => ['UserController', 'create'],
        '/users/edit' => ['UserController', 'edit'],
        '/users/delete-ajax' => ['UserController', 'deleteAjax'],
        '/products/create' => ['ProductController', 'create'],
        '/products/edit' => ['ProductController', 'edit'],
        '/products/delete' => ['ProductController', 'delete'],
    ],
];
